name: 'build'

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    strategy:
      matrix:
        node: [20]
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Install dependencies
        run: cd packages/web3-circle-sdk && yarn install
      - name: Build project
        run: cd packages/web3-circle-sdk && yarn build

  test:
    needs: build
    strategy:
      matrix:
        node: [20]
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Run tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SECRET: ${{ secrets.SECRET }}
        run: cd packages/web3-circle-sdk && yarn test:e2e

  lint:
    needs: build
    strategy:
      matrix:
        node: [20]
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Run linter
        run: yarn lint
